### ISSUE TITLE
C emum types representation inconsistency

### ISSUE THREAD

**Issue by cheblin** [rust-lang/rust-bindgen#1528] opened 2019-03-03 02:56 UTC
for C enum
```C
typedef enum
{
	PROCESS_CHANNEL_REQEST = 0x7fffffff,
	PROCESS_HOST_REQEST = 0x7fffffff - 1,
	PROCESS_RECEIVED_PACKS = 0x7fffffff - 2,
} PROCESS;
```

on MACOS rust-bindgen generate 

```Rust
pub const PROCESS_PROCESS_CHANNEL_REQEST: PROCESS = 2147483647;
pub const PROCESS_PROCESS_HOST_REQEST: PROCESS = 2147483646;
pub const PROCESS_PROCESS_RECEIVED_PACKS: PROCESS = 2147483645;

pub type PROCESS    = u32;
```

on Windows

```Rust
pub const PROCESS_PROCESS_CHANNEL_REQEST: PROCESS = 2147483647;
pub const PROCESS_PROCESS_HOST_REQEST: PROCESS = 2147483646;
pub const PROCESS_PROCESS_RECEIVED_PACKS: PROCESS = 2147483645;

pub type PROCESS      = i32;
```

**Comment by emilio** [comment] 2019-03-03 04:47
This is the type the underlying platform uses, so bindgen is doing the right thing.

This is a duplicate of #1244.

**Closed by emilio** 2019-03-03 04:47 UTC
