### ISSUE TITLE
link error undefined reference 

### ISSUE THREAD

**Issue by toplinuxsir** [rust-lang/rust-bindgen#1890] opened 2020-09-03 00:08 UTC
I link c++ libray (libmylib.so ) , with g++ -lmylib , It works ok, and link success,
But with rust ,I have pass the -lmylib, compiles ok, and always link error:
'
 /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x106): undefined reference to `USB5622E_GetNetCfgA'
          /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x351): undefined reference to `USB5622E_AI_GetRateInfo'
          /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x4d0): undefined reference to `USB5622E_AI_VerifyParam'
          /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x4f7): undefined reference to `USB5622E_AI_InitTask'
          /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x508): undefined reference to `USB5622E_AI_StartTask'
          /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x581): undefined reference to `USB5622E_AI_SendSoftTrig'
          /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x5a0): undefined reference to `USB5622E_AI_ReadBinary'
          /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x875): undefined reference to `USB5622E_DEV_Release'
          /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x961): undefined reference 
'

**Comment by emilio** [comment] 2020-09-03 00:44
Bindgen doesn't take care of linking anything. Are you passing the right flags to rustc? Like `println!("cargo:rustc-link-lib=mylib")` from build.rs or such?

**Comment by toplinuxsir** [comment] 2020-09-03 02:40
@emilio 
Yes, I have pass the right flags to rustc

**Comment by nagisa** [comment] 2020-09-03 21:47
I started hitting something similar recently. More often than not it is because rustc reorders the `-l` flags before their use because it is missing the dependency information due to missing `#[link(name="...")]`.

**Comment by toplinuxsir** [comment] 2020-09-03 23:34
@nagisa How to resolve it  ? Thanks

**Comment by emilio** [comment] 2020-11-13 19:53
I think this is not a bindgen issue itself given the above... But a minimal repro would go a long way. Please reopen if this turns out to be an issue that should be fixed in bindgen.

**Closed by emilio** 2020-11-13 19:53 UTC

**Comment by nagisa** [comment] 2020-11-13 20:09
@emilio bindgen currently does not provide the means to add `#[link(name="...")]` attributes to extern blocks it generates. Something like [this](https://gitlab.com/nagisa/sample-example-for-rust-bernacle/tree/master) reproducer from https://github.com/rust-lang/rust/issues/65610 should be trivially adaptable to use bindgen.

**Comment by mrozekma** [comment] 2021-02-27 05:57
I'm a bindgen novice, but am confused why this isn't a bigger problem for users. I have to edit the generated bindings to add `#[link(...)]` attributes on the functions or the final link will fail when I try to call them, but the documentation seems to expect I'll just be able to use the generated bindings as-is.

**Comment by mengwanguc** [comment] 2021-09-05 21:33
I totally agree with @mrozekma , and I do think it's a big problem for me as I need to add `#[link(name="...")]` manually for every function I'm calling in the generated "binding.rs". bindgen should be able to do it for users
