### ISSUE TITLE
Allow statically linking libclang

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust-bindgen#1617] opened 2019-09-11 23:10 UTC
The bindgen Cargo.toml mentions a "static" feature, but it doesn't seem to connect to anything. Its dependency on clang-sys always sets the "runtime" features, which forces runtime dynamic loading.

I'd like to build bindgen statically linked with libclang, mostly to make deployment easier. It would be nice to be able to pass the "static" feature through to clang-sys rather than always requiring "runtime".

**Comment by jsgf** [comment] 2019-09-13 17:36
I have a PR in progress.

**Comment by emilio** [comment] 2019-09-14 02:45
Sweet! :)

**Comment by emilio** [comment] 2019-10-28 12:04
Fixed by #1620 and #1649.

**Closed by emilio** 2019-10-28 12:04 UTC
Labels: enhancement, help wanted

**Comment by jethrogb** [comment] 2021-04-14 08:58
This is the cause of #2030
