### ISSUE TITLE
Bindgen does not generate bindings for declarations in a `extern "C"` block

### ISSUE THREAD

**Issue by tokatoka** [rust-lang/rust-bindgen#2707] opened 2024-01-04 15:13 UTC
Sorry if this is a duplicate issue. but I could not find any related issue.
My problem is that if the declaration is in extern "C" block, then the binding are not generated.

### Input C/C++ Header

```C++
void foo();

extern "C" {
	void bar();
}
```
Save this as foo.h

### Bindgen Invocation

```Rust
use std::env;
fn main() {
    let args: Vec<String> = env::args().collect();

    let rust_bindings = bindgen::Builder::default()
        .clang_args(["-x", "c++", "-std=c++17"].iter())
        .header(
            &args[1]
        )
        .generate()
        .unwrap();

    println!("{:#?}", rust_bindings.to_string());
}

```

or

```bash
$ bindgen ./foo.h -- -x c++
```

### Actual Results

This is the result from 
```bash
$ bindgen ./foo.h -- -x c++
```

but the result does not have the bindings for `bar()`.
```
/* automatically generated by rust-bindgen 0.69.1 */

extern "C" {
    #[link_name = "\u{1}_Z3foov"]
    pub fn foo();
}

```
### Expected Results

It should be like 
```
/* automatically generated by rust-bindgen 0.69.1 */

extern "C" {
    #[link_name = "\u{1}_Z3foov"]
    pub fn foo();

    pub fn bar();
}
```

Am I missing some options?

### Additional notes
The bindgen 0.59.1 (which I can install with apt on ubuntu 22.04) does generate the correct result though
```
$ /usr/bin/bindgen foo.h -- -x c++
/* automatically generated by rust-bindgen 0.59.1 */

extern "C" {
    #[link_name = "\u{1}_Z3foov"]
    pub fn foo();
}
extern "C" {
    pub fn bar();
}
$ /usr/bin/bindgen --version
bindgen 0.59.1
```

**Comment by tokatoka** [comment] 2024-01-04 16:15
When I uninstalled libclang-18 and installed libclang-17 then things works again.
I'd assume something is wrong with llvm/clang-18

**Comment by vpalatin** [comment] 2024-01-11 17:22
This might be what https://github.com/rust-lang/rust-bindgen/commit/86f3dbe846020e2ba573d6eb38d1434d0cbcbb40 is fixing

**Comment by vpalatin** [comment] 2024-01-11 19:28
@emilio 
will the [commit mentioned above ](https://github.com/rust-lang/rust-bindgen/commit/86f3dbe846020e2ba573d6eb38d1434d0cbcbb40) be released soon ?

On systems with LLVM-18, bindgen is silently breaking (writing bindings with missing functions) and failing the build of Rust programs which were working before.

**Comment by emilio** [comment] 2024-01-13 00:20
Dupe of #2689. I did a 0.69.2 release with just the fix (since there have been breaking changes on top of 0.69.1 already). https://github.com/rust-lang/rust-bindgen/releases/tag/v0.69.2

**Closed by emilio** 2024-01-13 00:20 UTC
