### ISSUE TITLE
define with type cast not begin generated

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust-bindgen#1585] opened 2019-06-27 14:45 UTC
### Input C/C++ Header

```C++
#define FOO 3
#define BAR ((uint32_t)FOO)
#define BAZ ((uint32_t)5)
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```rust
pub const FOO: u32 = 3;
```

### Expected Results

```rust
pub const FOO: u32 = 3;
pub const BAR: u32 = 3;
pub const BAZ: u32 = 5
```

This seems to be related to the type cast. Not sure why the values won't be produced

**Comment by emilio** [comment] 2019-06-27 17:29
Dupe of #316, see there for details.

There's progress on this in https://github.com/jethrogb/rust-cexpr/pull/15

**Closed by emilio** 2019-06-27 17:29 UTC
