### ISSUE TITLE
Anonymous variants: Ability to override the output integer type

### ISSUE THREAD

**Issue by amanjeev** [rust-lang/rust-bindgen#2392] opened 2023-01-18 19:44 UTC
### Input C/C++ Header

```C++
enum {
    SCREEN_APPLICATION_CONTEXT = 0,
};
```

### Bindgen Invocation

```
$ bindgen input.h 
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.63.0 */

pub const SCREEN_APPLICATION_CONTEXT: _bindgen_ty_1 = 0;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
```

### Expected Results

User wants the ability to override the integer type from `u32` to `i32` in the output.

**Comment by pvdrz** [comment] 2023-01-20 03:55
This should be relatively straightforward to implement as we already do something similar with `#define` macros. The only real question here is how do we expose this? Through regular flags/options? using callbacks? should we add a new callback for this? or reuse one of the existing ones? etc

**Comment by pvdrz** [comment] 2023-02-10 20:49
Closing as duplicate of https://github.com/rust-lang/rust-bindgen/issues/1907

**Closed** 2023-02-10 21:00 UTC
