### ISSUE TITLE
`rewriting static` string in generated bindings

### ISSUE THREAD

**Issue by robin-nitrokey** [rust-lang/rust-bindgen#2852] opened 2024-06-24 09:21 UTC
### Input C/C++ Header

```C++
#define test 0
```

### Bindgen Invocation

```
$  cargo --version
cargo 1.81.0-nightly (bc89bffa5 2024-06-22)
$ git describe
v0.69.1-94-gcf9b02f5
$ cargo run -- repro.h
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.69.4 */

rewriting static
pub const test: u32 = 0;
```

### Expected Results

The generated bindings should compile properly and not contain arbitrary strings.

notes:

- even occurs with 0.69.4 from crates.io and when invoking `Builder::generate` from `build.rs`
- only occurs since nightly-2024-06-23, nightly-2024-06-22 still works

**Comment by emilio** [comment] 2024-06-24 09:50
On which OS? This works for me on trunk and on the crates.io crate... that string is nowhere in the source code...

**Comment by chrysn** [comment] 2024-06-24 10:03
We're having similar trouble in our setup. A commonality between those is that we're also more "in the embedded area". We haven't managed to track down the source of the string either, but I did find that it is emitted as part of the bindgen generation (an strace shows that the odd string is written in the same write call as the rest of what our bindings.wrtite_to_file produces).

I can reproduce this on Debian GNU/Linux with a current nightly Rust installed through rustup; the issue does not appear with stable.

**Comment by chrysn** [comment] 2024-06-24 10:13
Correction: The string is *not* necessarily written in the same process: I mistook the contiguious read from the built file for a write.

The write actually originates from a some process writing it to file descriptor 1, its stdout -- which makes the whole thing appear more like some printf that escaped debugging.

**Comment by chrysn** [comment] 2024-06-24 10:15
… and it is rustfmt, where it is already reported: https://github.com/rust-lang/rustfmt/issues/6210

(So I'd guess this is a duplicate, and we all wait for a new nightly where the offending line is reverted).

**Comment by emilio** [comment] 2024-06-24 10:24
Thanks! Yeah let´s close as a dupe of https://github.com/rust-lang/rustfmt/issues/6210

**Closed by emilio** 2024-06-24 10:24 UTC

**Comment by ghenry** [comment] 2024-07-25 13:47
I'm getting this when converting [SentryPeer conf](https://github.com/SentryPeer/SentryPeer/blob/main/src/conf.h) to their [Rust bindings](https://github.com/SentryPeer/SentryPeer/blob/main/sentrypeer_rust/src/sentrypeer_conf.rs)

868 times! Any ideas?

Running:

`bindgen conf.h -o ../sentrypeer_rust/src/sentrypeer_conf_.rs`

**Comment by chrysn** [comment] 2024-07-25 13:54
Update your Rust nightly version, going forward 1-2 days will suffice.

**Comment by ghenry** [comment] 2024-07-25 14:28
Ah, I totally forgot I was on nightly. I was doing some miri stuff for finding a leak for a book I'm writting. Thanks!

How did you spot that?

**Comment by chrysn** [comment] 2024-07-25 14:52
That was a weird day, everyone was looking for it at the same time (and,
as it happened in this issue, reported it all over downstream to ensure
there is something referencable). I myself first (obviously, in
hindsight) had trouble reproducing the CI failures until I updated
nightly, and eventually looked at strace output to see where those
strange strings were coming from). At the time I had it, the rustfmt
issue was already open and almost fixed.

**Comment by ghenry** [comment] 2024-07-25 15:00
Oh, wow. Something hard to forget then! Thanks for replying so quickly.
