### ISSUE TITLE
Don't generate bindings for all headers

### ISSUE THREAD

**Issue by KernelErr0r** [rust-lang/rust-bindgen#1788] opened 2020-05-17 23:32 UTC
Is there an easy way to tell bindgen to not generate bindings to libc or winapi? I don't wanna do --blacklist-type and --blacklist-function like 30000 times (I can't really use --whitelist-type or --whitelist-function because there is no pattern in these names).
If not, I would propose to add something like --whitelist-header and --blacklist-header, example: --blacklist-header windows.h (It will ignore only this particular header, not all headers used by that header)

**Comment by emilio** [comment] 2020-05-19 00:47
The problem with this is two:

 * A C type can come from multiple headers, either via forward declarations, or via duplicate typedefs or signatures. So it's a bit tricky.

 * Bindgen would still have to parse the whole thing anyway.

But this is not impossible, just a bit hard and with edge cases all over the place. This is in any case a dupe of #303.

**Closed by emilio** 2020-05-19 00:47 UTC
