### ISSUE TITLE
Bindgen does not generate data of binary blob arrays

### ISSUE THREAD

**Issue by oblique** [rust-lang/rust-bindgen#1524] opened 2019-02-21 19:37 UTC
I have a case where I need to convert some headers which contain binary blob arrays.
Bindgen only generates their name. Below I have a minimal example.

### Input C/C++ Header

```C++
static const unsigned char data[] = {
    0x01, 0x02, 0x03, 0x04
};
```

### Bindgen Invocation

```
$ bindgen input.h
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

extern "C" {
    #[link_name = "\u{1}data"]
    pub static mut data: [::std::os::raw::c_uchar; 4usize];
}
```

### Expected Results

I'm not sure what would be the best result, but something similar to:

```rust
pub const data: [::std::os::raw::c_uchar; 4usize] = [0x01, 0x02, 0x03, 0x04];
```

**Comment by emilio** [comment] 2019-02-21 21:55
Dupe of #1266. We have no way of accessing this information from clang atm.

Adding such an API to libclang shouldn't be too hard, if someone was motivated enough. I'm happy to help out with that, but I doubt I'd have enough time to do it myself.

**Closed by emilio** 2019-02-21 21:55 UTC
