### ISSUE TITLE
hundreds of new "dereferencing a null pointer" warnings when compiling against rust 1.53

### ISSUE THREAD

**Issue by joseluis** [rust-lang/rust-bindgen#2066] opened 2021-06-18 09:23 UTC
When compiling a project with Rust 1.53, hundredds of new warnings have appeared which didn't happen with Rust 1.52. They are all like this:

```
warning: dereferencing a null pointer
    --> (...)/target/debug/build/libnotcurses-sys-8d04446a4713669a/out/bindings.rs:1409:19
     |
1409 |         unsafe { &(*(::core::ptr::null::<sigaction>())).sa_handler as *const _ as usize },
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this code causes undefined behavior when executed
```

**Comment by nbdd0121** [comment] 2021-06-18 11:38
Duplicate of #1651

**Comment by jmjoy** [comment] 2021-06-19 02:02
Temporary use `#![allow(deref_nullptr)]` to suppress.

**Comment by emilio** [comment] 2021-06-19 08:33
Yup, let's track it in #1651.

**Closed by emilio** 2021-06-19 08:33 UTC
