### ISSUE TITLE
warning: dereferencing a null pointer

### ISSUE THREAD

**Issue by lucas-zee** [rust-lang/rust-bindgen#2142] opened 2021-12-20 14:05 UTC
This is some code generated by bindgen:

```
assert_eq!(
		unsafe {
			&(*(::std::ptr::null::<max_align_t>())).__clang_max_align_nonce2 as *const _ as usize
		},
		16usize,
		concat!(
			"Offset of field: ",
			stringify!(max_align_t),
			"::",
			stringify!(__clang_max_align_nonce2)
		)
	);
```

gives

```
warning: dereferencing a null pointer
   --> /workspaces/my_rust_project/target/debug/build/my_rust_project-8b92ea2f54bf11a3/out/bindings.rs:540:5
    |
540 |             &(*(::std::ptr::null::<max_align_t>())).__clang_max_align_nonce2 as *const _ as usize
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this code causes undefined behavior when executed
```

is this intended? If so, then shouldn't this error be disabled?

**Comment by lucas-zee** [comment] 2021-12-20 14:06
full code:

```
#[test]
fn bindgen_test_layout_max_align_t() {
	assert_eq!(
		::std::mem::size_of::<max_align_t>(),
		32usize,
		concat!("Size of: ", stringify!(max_align_t))
	);
	assert_eq!(
		::std::mem::align_of::<max_align_t>(),
		16usize,
		concat!("Alignment of ", stringify!(max_align_t))
	);
	assert_eq!(
		unsafe {
			&(*(::std::ptr::null::<max_align_t>())).__clang_max_align_nonce1 as *const _ as usize
		},
		0usize,
		concat!(
			"Offset of field: ",
			stringify!(max_align_t),
			"::",
			stringify!(__clang_max_align_nonce1)
		)
	);
	assert_eq!(
		unsafe {
			&(*(::std::ptr::null::<max_align_t>())).__clang_max_align_nonce2 as *const _ as usize
		},
		16usize,
		concat!(
			"Offset of field: ",
			stringify!(max_align_t),
			"::",
			stringify!(__clang_max_align_nonce2)
		)
	);
}
```

**Comment by emilio** [comment] 2021-12-20 14:09
Dupe of #1651.

**Comment by emilio** [comment] 2021-12-20 14:09
(Thanks for reporting though!)

**Closed by emilio** 2021-12-20 14:09 UTC
