### ISSUE TITLE
The target passed to clang is wrong for aarch64-apple-darwin

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust-bindgen#1871] opened 2020-08-13 21:20 UTC
bindgen passes the rust target unchanged, but unfortunately, in the case of aarch64-apple-darwin, the clang target is different, and clang doesn't recognize aarch64-apple-darwin at all. The right target to use is arm64-apple-darwin.

**Comment by kulp** [comment] 2020-08-14 03:37
Was this issue possibly fixed by d55b063e8010a3acf5c2a549a1d2d7c238286314 ?

**Comment by glandium** [comment] 2020-08-14 03:49
Only when building on an Apple Silicon DTK with an arm64 rustc.

**Comment by simlay** [comment] 2020-08-14 05:02
#1211 seems like this could be a related issue.

**Comment by glandium** [comment] 2020-08-14 07:54
Yes, it's the exact same thing.

**Comment by emilio** [comment] 2020-08-14 10:31
Ok, let's close as a dupe of #1211 and fix it there. Thanks @glandium!

**Closed by emilio** 2020-08-14 10:31 UTC
