### ISSUE TITLE
generate shell completion is changed in v0.71.0

### ISSUE THREAD

**Issue by daeho-ro** [rust-lang/rust-bindgen#3037] opened 2024-12-07 01:47 UTC
Hello,

I have noticed that the generating shell completion is a bit weird now, 

```
bindgen --generate-shell-completions 
error: a value is required for '--generate-shell-completions <SHELL>' but none was supplied
  [possible values: bash, elvish, fish, powershell, zsh]

For more information, try '--help'.
```

The option  `--generate-shell-completions` requires shell input and so put it leads to an error

```
bindgen --generate-shell-completions bash
error: the following required arguments were not provided:
  <HEADER>

Usage: bindgen <FLAGS> <OPTIONS> <HEADER> -- <CLANG_ARGS>...

For more information, try '--help'.
```

It seems that the usage is changed and not documented on the command.

This is happen on the homebrew CI here,
- https://github.com/Homebrew/homebrew-core/pull/200347

Thanks,

**Comment by jbeich** [comment] 2024-12-07 04:03
Duplicate of https://github.com/rust-lang/rust-bindgen/issues/2677#issuecomment-1789663526 ?

**Comment by jbeich** [comment] 2024-12-07 04:12
FWIW, you can work around the required argument (header) by passing a dummy/garbage e.g., `bindgen --generate-shell-completions bash /dev/null`

**Closed** 2024-12-08 15:47 UTC
