### ISSUE TITLE
bindgen startup is incredibly slow

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust-bindgen#1532] opened 2019-03-06 12:25 UTC
Just running `bindgen` without any parameters, just displaying the help text, takes 2 seconds:
```
$ time bindgen
error: The following required arguments were not provided:
    <header>

USAGE:
    bindgen [FLAGS] [OPTIONS] <header> -- <clang-args>...

For more information try --help

real	0m1.984s
user	0m1.085s
sys	0m0.810s
```

Investigating this a little, the `strace` shows that it goes through every file in a couple of directories, like `/usr/lib`, etc.:
```
$ strace -ffobindgen bindgen
error: The following required arguments were not provided:
    <header>

USAGE:
    bindgen [FLAGS] [OPTIONS] <header> -- <clang-args>...

For more information try --help
$ grep stat bindgen | wc -l
126542
$ grep getdents bindgen | wc -l
12039
```

I don't think bindgen needs to do 100k stat calls for startup, scanning my entire /usr/bin and /usr/lib.

**Comment by emilio** [comment] 2019-03-06 14:09
cc @KyleMayes, not sure if you have any ideas about how to speed up finding the libclang path...

**Comment by KyleMayes** [comment] 2019-03-09 23:58
If startup time is a concern, you could set the `CLANG_PATH` environment variable which is a path to the `clang` executable you want to use. This will bypass searching the filesystem in favor of blindly using the path provided by the environment variable.

**Comment by tbu-** [comment] 2019-03-10 14:34
If it's just looking for a `clang` executable, why is it not just looking in `PATH`?
```
$ time which clang
/usr/bin/clang

real	0m0.032s
user	0m0.000s
sys	0m0.004s
$ time bindgen
error: The following required arguments were not provided:
    <header>

USAGE:
    bindgen [FLAGS] [OPTIONS] <header> -- <clang-args>...

For more information try --help

real	0m21.136s
user	0m1.424s
sys	0m2.187s
```

(Both on empty file system caches this time.)

`which` find my clang executable more than two orders of magnitude faster.

**Comment by emilio** [comment] 2019-03-10 18:33
Maybe this issue should be moved to clang-sys? I'm happy to upgrade the dependency to pull a fix for this. On bindgen's side we cannot really workaround it as much. I could special-case the `--help` or errors to not look at libclang and such, but that'd only help with those, not with general bindgen usage.

**Comment by kulp** [comment] 2022-03-16 01:18
It is not clear how to reproduce this issue, but since it was filed, dynamic and static linking became available in 5915768cb037576c3bd68505ede94fdffffdb0e3, and I speculate that any runtime slowness would be due to runtime searching for a library (using `clang-sys`'s `runtime` feature) which could be mitigated by switching to static or dynamic linking (for example, `cargo build --no-default-features --features=clap` to build `bindgen` with dynamic-but-not-runtime linking).

Consequently I am optimistically closing this issue. Please reopen it if it can be reproduced again.

**Closed by kulp** 2022-03-16 01:18 UTC
Labels: bug, A-libclang

**Comment by tbu-** [comment] 2022-03-16 18:02
Indeed, the issue doesn't exist anymore (at the very least for printing the help message, haven't investigated further).

```
$ time bindgen
error: The following required arguments were not provided:
    <header>

USAGE:
    bindgen [FLAGS] [OPTIONS] <header> -- <clang-args>...

For more information try --help

real	0m0.003s
user	0m0.000s
sys	0m0.003s
```

Also, the syscalls seem a lot more reasonable now:
```
$ strace -ffobindgen bindgen
[...]
$ grep getdents bindgen.* | wc -l
0
$ grep stat bindgen.* | wc -l
7
```

Thanks for fixing this issue (maybe unintentionally? :P).

**Comment by kulp** [comment] 2022-03-17 00:58
Sometimes happy accidents do happen ! Thanks for the confirmation.
