### ISSUE TITLE
Move away from "whitelist"/"blacklist" terminology

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-bindgen#1997] opened 2021-02-16 16:04 UTC
Bindgen currently uses "whitelist" and "blacklist" terminology in its flags. The Rust project and the industry in general have been slowly moving off of these due to their negative implications (https://github.com/rust-lang/rust/pull/74150, https://github.com/rust-lang/rust-clippy/pull/5896), perhaps we should do the same here? I think we can keep an alias for backwards compatibility, but document allowlist/denylist instead.

**Comment by emilio** [comment] 2021-02-16 16:12
Dupe of #1812, there's a patch about to land in #1990.

**Closed by emilio** 2021-02-16 16:12 UTC

**Comment by Manishearth** [comment] 2021-02-16 17:02
wow, amazing timing
