### ISSUE TITLE
Feature request: custom derives

### ISSUE THREAD

**Issue by tbodt** [rust-lang/rust-bindgen#2024] opened 2021-04-05 18:28 UTC
I want to be able to add custom traits to the `#[derive(` on Bindgen types. My specific use case is the `FromBytes` derive from https://docs.rs/zerocopy. This might look something like this:

```
bindgen::Builder::default()
    .header("input.h")
    .raw_line("use zerocopy::FromBytes;")
    .derive_custom("FromBytes")
    .generate()
    .unwrap()
```

**Comment by emilio** [comment] 2021-04-06 09:35
Dupe of #1089, probably should be keyed per-type? If so this should be reasonably straight-forward. If not, we might need more information to know when something can be derived or not...

**Closed by emilio** 2021-04-06 09:35 UTC
