### ISSUE TITLE
Rename Builder::whitelist/blacklist?

### ISSUE THREAD

**Issue by saschanaz** [rust-lang/rust-bindgen#1961] opened 2020-12-31 20:27 UTC
Builder has several uses of the words e.g. [blacklist_type](https://docs.rs/bindgen/0.56.0/bindgen/struct.Builder.html#method.blacklist_type), could they be deprecated and replaced with better words?

**Comment by kulp** [comment] 2020-12-31 21:10
This seems to be a duplicate of #1812. Feel free to continue discussion there if you think there is something new to add.

**Closed by kulp** 2020-12-31 21:10 UTC
