### ISSUE TITLE
Missing #define when bit shifting?

### ISSUE THREAD

**Issue by Geobert** [rust-lang/rust-bindgen#1642] opened 2019-10-08 14:54 UTC
```C++
enum MY_Status_t
{
    SHIFT0 = 0,
    SHIFT1,
};

#define MY_VAL1 (1 << SHIFT1)
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
        .clang_args(&["-target", "thumbv7em-none-eabihf"])
        .layout_tests(false)
        .generate_comments(false)
        .use_core()
        .whitelist_function("MY_.*")
        .whitelist_var("MY_.*")
        .whitelist_type("MY_.*")
        .header("wrapper.h")
        .generate()
        .expect("Unable to generate bindings");
```

### Actual Results

```rust
/* automatically generated by rust-bindgen */

pub const MY_Status_t_SHIFT0: MY_Status_t = 0;
pub const MY_Status_t_SHIFT1: MY_Status_t = 1;
pub type MY_Status_t = u32;

```
### Expected Results

MY_VAL1 should be converted to something similar to:
```rust
pub const MY_VAL1: u32 = 1 << MY_Status_t_SHIFT1;
```

Shouldn't it? (I'm not sure)

**Comment by emilio** [comment] 2019-10-08 17:30
Dupe of #258, but this is really not quite fixable without some sort of heuristic (see similar requests for struct names https://github.com/rust-lang/rust-bindgen/issues/1546, struct definitnions (https://github.com/rust-lang/rust-bindgen/issues/1044), etc...

This works as expected if you had something like:

`const unsigned MY_VAL1 = (1 << SHIFT1);` in the C / C++ code.

**Closed by emilio** 2019-10-08 17:30 UTC
