### ISSUE TITLE
FR: generate enum for macro constants with a common prefix

### ISSUE THREAD

**Issue by yshui** [rust-lang/rust-bindgen#2456] opened 2023-03-21 23:56 UTC
### Input C/C++ Header

```C++
#define CONST_A 1
#define CONST_B 2
#define CONST_C 3
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
    .header("input.h")
    .generate()
    .unwrap()
```

### Current state

```rust
pub const CONST_A: u32 = 1;
pub const CONST_B: u32 = 2;
pub const CONST_C: u32 = 3;
```

### Desired state

there is a option I can enable, to change the output to this:

```rust
pub enum Const {
    A = 1,
    B = 2,
    C = 3,
}
```

**Comment by pvdrz** [comment] 2023-03-22 05:00
Closing as duplicate of https://github.com/rust-lang/rust-bindgen/issues/2174

**Closed by pvdrz** 2023-03-22 05:00 UTC
