### ISSUE TITLE
Bindgen problem [help wanted]

### ISSUE THREAD

**Issue by hanusek** [rust-lang/rust-bindgen#1942] opened 2020-12-13 19:00 UTC
Hello.
I'm trying bind C library - [ Xenomai 3 RT Framework ](https://gitlab.denx.de/Xenomai/xenomai/-/tree/stable/v3.0.x)to Rust.
I'm using bindgen. I need help.

I did it before:
```
apt install llvm-dev libclang-dev clang
```
### Input C/C++ Header
https://gitlab.denx.de/Xenomai/xenomai/-/blob/stable/v3.0.x/include/alchemy/queue.h

### Bindgen Invocation
```
$ bindgen ./xenomai/include/alchemy/queue.h -o ./binds.rs -- -I./xenomai/include
```

### Actual Results

```
xenomai-sys/xenomai/include$ bindgen alchemy/queue.h -o ../binds.rs -- -I. -I../lib  -I/var/lib/cloud9/xenomai-sys/xenomai/lib/cobalt/arch/arm/include -I./cobalt
thread 'main' panicked at '`libclang` function not loaded: `clang_Cursor_isFunctionInlined`. This crate requires that `libclang` 3.9 or later be installed on your system. For more information on how to accomplish this, see here: https://rust-lang.github.io/rust-bindgen/requirements.html#installing-clang-39', /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.0.3/src/lib.rs:1672:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 9
```

**Comment by emilio** [comment] 2020-12-20 15:47
Which libclang version are you using? This function is supported in clang 3.9+. We dropped support for those a bit ago see #1830 etc.

**Comment by emilio** [comment] 2020-12-20 15:47
If the issue is a too old libclang I think this is wontfix unfortunately.

**Closed** 2020-12-23 21:15 UTC
