### ISSUE TITLE
Allow custom derives and attributes

### ISSUE THREAD

**Issue by RReverser** [rust-lang/rust-bindgen#1089] opened 2017-10-18 17:51 UTC
Several times I found myself in need to derive traits that are not autogenerated by bindgen, and, unfortunately, Rust doesn't allow to put a `derive` directive (or any attribute) at distance from the original type, even in the same file.

Would it make sense to provide ability to add custom derives or even any attributes to generated types via `ParseCallbacks` or some other mechanism?

**Comment by fitzgen** [comment] 2017-10-23 16:36
This seems like a good feature to have.

I'd prefer not using `ParseCallbacks` if possible, because avoiding them allows easier testing, and I believe that custom derives is specific enough that it doesn't need the open ended programmatic access that `ParseCallbacks` provides.

As far as CLI syntax: `--custome-derive '<trait>=<regex>'`?

**Comment by RReverser** [comment] 2017-10-23 17:18
@fitzgen Thing is, some derives still accept options via extra attributes (for example, https://github.com/kwohlfahrt/enum-tryfrom), so I'm not sure if it's worth locking up to just trait name.

**Comment by fitzgen** [comment] 2017-10-23 17:25
Good catch. I guess that it does make sense to have an escape hatch for more complicated cases in `ParseCallbacks` -- but I'd still prefer the simple versions to be supported on the CLI for easier testing (and in general it is best when things are usable in either scenario).

**Comment by RReverser** [comment] 2017-10-23 17:29
What do you think about the attribute approach then? (allowing any attributes to be appended)
Should be still CLI compatible while allowing these more complex cases.

**Comment by fitzgen** [comment] 2017-10-23 17:36
Sorry I totally thought throught that stuff in my head and then failed to leave any comment about it :-p

The problem is that we would need to parse arbitrary attributes to know which `=` we are splitting on between the attr and the regex. This is because of attrs like `#[serde(rename = "blah")]`. I guess we could use https://dtolnay.github.io/syn/syn/fn.parse_outer_attr.html, but that signature doesn't seem to allow trailing bits or return where the parsing ended...

**Comment by RReverser** [comment] 2017-10-23 17:40
@fitzgen Maybe could use some other delimiter then, like "=>" or whatever?

**Comment by RReverser** [comment] 2017-10-23 17:42
Or, actually, could as well put the regexp first and start at "#" then like `regex#[derive(Default)]`.

**Comment by fitzgen** [comment] 2017-10-23 17:56
Yeah, I think that works

**Comment by joelgallant** [comment] 2019-02-15 05:22
This would be nice for serde derives

**Comment by meme** [comment] 2019-10-04 22:39
Looking for this as well, willing to work on it -- has any work since been done?

**Comment by emilio** [comment] 2021-04-06 09:34
I don't think there has been much progress here, but I don't think this should be particularly hard to implement, happy to help.

**Comment by tbodt** [comment] 2021-04-06 17:40
I want my derive to apply to all structs, which would simplify the implementation for me. Perhaps I can implement that and leave it open to be extended to a regex?

**Comment by trobanga** [comment] 2021-11-07 18:15
It would be nice, if it would work with enums too. If I'm right then the current implementation of #2059 does only work with structs, or does it?

**Comment by ericseppanen** [comment] 2021-11-07 21:47
> It would be nice, if it would work with enums too. If I'm right then the current implementation of #2059 does only work with structs, or does it?

I agree, it doesn't seem to work.

**Comment by pvdrz** [comment] 2022-09-20 20:52
I'm closing this issue as the enums support was fixed in #2117

**Closed by pvdrz** 2022-09-20 20:52 UTC
Labels: enhancement, E-less-easy
