### ISSUE TITLE
bindgen generating `i64` instead of `u64`

### ISSUE THREAD

**Issue by redeexpressos** [rust-lang/rust-bindgen#2874] opened 2024-07-30 09:11 UTC
### Input C/C++ Header

```C++
#define UAVCAN_PROTOCOL_GETNODEINFO_REQUEST_SIGNATURE (0xEE468A8121C46A9EULL)
```

### Bindgen Invocation

```Rust
    let bindings = bindgen::Builder::default()
        .clang_arg("-Iexternal/libcanard")
        .header("wrapper.h")
        .generate()
        .expect("Unable to generate bindings");
```

```rs
pub const UAVCAN_PROTOCOL_GETNODEINFO_REQUEST_SIGNATURE: i64 = -1277181157091022178;
```
### Expected Results

Shouldnt it generate an `u64`?

**Comment by ojeda** [comment] 2024-07-30 09:56
See as well https://github.com/rust-lang/rust-bindgen/issues/2120 and https://github.com/rust-lang/rust-bindgen/issues/1594.

**Comment by pvdrz** [comment] 2024-09-07 08:03
yep closing as duplicate of https://github.com/rust-lang/rust-bindgen/issues/1594

**Closed by pvdrz** 2024-09-07 08:03 UTC
