### ISSUE TITLE
Objective-C anonymous category need to be merged to main type

### ISSUE THREAD

**Issue by youknowone** [rust-lang/rust-bindgen#2241] opened 2022-07-21 21:48 UTC
### Input C/C++ Header

```objc
@interface X
@property(readonly) int p0;
@end

@interface X ()
@property(readonly) int p1;
@end

@interface X ()
@property(readonly) int p2;
@end
```

### Bindgen Invocation

```
$ bindgen anon_interface.m
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.60.1 */

use objc::{self, class, msg_send, sel, sel_impl};
#[allow(non_camel_case_types)]
pub type id = *mut objc::runtime::Object;
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct X(pub id);
impl std::ops::Deref for X {
    type Target = objc::runtime::Object;
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.0 }
    }
}
unsafe impl objc::Message for X {}
impl X {
    pub fn alloc() -> Self {
        Self(unsafe { msg_send!(class!(X), alloc) })
    }
}
impl IX for X {}
pub trait IX: Sized + std::ops::Deref {
    unsafe fn p0(&self) -> ::std::os::raw::c_int
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(*self, p0)
    }
}
impl X_ for X {}
pub trait X_: Sized + std::ops::Deref {
    unsafe fn p1(&self) -> ::std::os::raw::c_int
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(*self, p1)
    }
}
impl X_ for X {}
pub trait X_: Sized + std::ops::Deref {
    unsafe fn p2(&self) -> ::std::os::raw::c_int
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(*self, p2)
    }
}
```

and

```
error[E0428]: the name `X_` is defined multiple times
  --> x.rs:40:1
   |
31 | pub trait X_: Sized + std::ops::Deref {
   | ------------------------------------- previous definition of the trait `X_` here
...
40 | pub trait X_: Sized + std::ops::Deref {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `X_` redefined here
   |
   = note: `X_` must be defined only once in the type namespace of this module
```

### Expected Results

```rust
use objc::{self, class, msg_send, sel, sel_impl};
#[allow(non_camel_case_types)]
pub type id = *mut objc::runtime::Object;
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct X(pub id);
impl std::ops::Deref for X {
    type Target = objc::runtime::Object;
    fn deref(&self) -> &Self::Target {
        unsafe { &*self.0 }
    }
}
unsafe impl objc::Message for X {}
impl X {
    pub fn alloc() -> Self {
        Self(unsafe { msg_send!(class!(X), alloc) })
    }
}
impl IX for X {}
pub trait IX: Sized + std::ops::Deref {
    unsafe fn p0(&self) -> ::std::os::raw::c_int
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(*self, p0)
    }

    unsafe fn p1(&self) -> ::std::os::raw::c_int
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(*self, p1)
    }

    unsafe fn p2(&self) -> ::std::os::raw::c_int
    where
        <Self as std::ops::Deref>::Target: objc::Message + Sized,
    {
        msg_send!(*self, p2)
    }
}
```

**Comment by emilio** [comment] 2022-07-25 09:28
cc @simlay

**Comment by youknowone** [comment] 2022-07-25 16:49
oh, this is duplication of #1889

**Comment by emilio** [comment] 2022-07-25 17:10
Thanks, closing as a dupe of https://github.com/rust-lang/rust-bindgen/issues/1889

**Closed** 2022-07-25 17:10 UTC
Labels: bug, A-Obj-C
