### ISSUE TITLE
Some value is missing in transforming such as '((__u64)0xAA)'

### ISSUE THREAD

**Issue by Unlimited-Witchcraft** [rust-lang/rust-bindgen#1697] opened 2019-12-17 02:16 UTC
When I transfrom some C linux system file.
```c
#define UFFD_API ((__u64)0xAA)
#define UFFD_API_FEATURES (UFFD_FEATURE_EVENT_FORK |        \
               UFFD_FEATURE_EVENT_REMAP |       \
               UFFD_FEATURE_EVENT_REMOVE |  \
               UFFD_FEATURE_EVENT_UNMAP |       \
               UFFD_FEATURE_MISSING_HUGETLBFS | \
               UFFD_FEATURE_MISSING_SHMEM |     \
               UFFD_FEATURE_SIGBUS |        \
               UFFD_FEATURE_THREAD_ID)
#define UFFD_API_IOCTLS             \
    ((__u64)1 << _UFFDIO_REGISTER |     \
     (__u64)1 << _UFFDIO_UNREGISTER |   \
     (__u64)1 << _UFFDIO_API)
#define UFFD_API_RANGE_IOCTLS           \
    ((__u64)1 << _UFFDIO_WAKE |     \
     (__u64)1 << _UFFDIO_COPY |     \
     (__u64)1 << _UFFDIO_ZEROPAGE)
#define UFFD_API_RANGE_IOCTLS_BASIC     \
    ((__u64)1 << _UFFDIO_WAKE |     \
     (__u64)1 << _UFFDIO_COPY)
```
Those values above are all missing.

**Comment by emilio** [comment] 2019-12-17 10:08
Dupe of https://github.com/rust-lang/rust-bindgen/issues/316. This is hard because how C macros work... You really don't know the value until the macro is evaluated in a context.

But this has a very easy workaround which is using it in a constant somewhere, which bindgen would understand, so:

```cpp
static const uint64_t kUffdApiRangeIoctls = UFFD_API_RANGE_IOCTLS; // Or whatever name you want
```

Then it'd work.

**Closed by emilio** 2019-12-17 10:08 UTC

**Comment by Unlimited-Witchcraft** [comment] 2019-12-18 07:07
> Dupe of #316. This is hard because how C macros work... You really don't know the value until the macro is evaluated in a context.
> 
> But this has a very easy workaround which is using it in a constant somewhere, which bindgen would understand, so:
> 
> ```c++
> static const uint64_t kUffdApiRangeIoctls = UFFD_API_RANGE_IOCTLS; // Or whatever name you want
> ```
> 
> Then it'd work.

Thank you for reply.
