### ISSUE TITLE
Failure to define static const strucs. Left with only declarations.

### ISSUE THREAD

**Issue by ephraimfeldblum** [rust-lang/rust-bindgen#2322] opened 2022-10-23 09:11 UTC
I'm trying to use a c header in my rust module, using bindgen to translate it, but bindgen seems to not parse it as well as it could have. It seems to be merely declaring the struct without defining it.

### Input C/C++ Header

```C++
typedef struct MyLib_Foo {
    uint64_t x;
    uint64_t y;
} MyLib_Foo;

static const MyLib_Foo MyLib_Bar = { 0, 1 }, MyLib_Baz = {...}, ...;
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
    .header("mylib.h")
    .allowlist_var("(MYLIB|MyLib).*")
    .allowlist_type("MyLib.*")
    .generate()
    .unwrap()
```

### Actual Results

```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MyLib_Foo {
    pub x: u64,
    pub y: u64,
}

extern "C" {
    pub static MyLib_Bar: MyLib_Foo;
}
...
```

```sh
$ nm -A -C path/to/library.so | grep MyLib_Bar
path/to/library.so:                 U MyLib_Bar
```

### Expected Results

```rust
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MyLib_Foo {
    pub x: u64,
    pub y: u64,
}

const MyLib_Bar: MyLib_Foo = MyLIb_Foo{x: 0, y: 1};
...
```

```sh
$ nm -A -C path/to/library.so | grep MyLib_Bar
path/to/library.so:xxxxxxxxxxxxxxxx r MyLib_Bar
```

**Comment by ephraimfeldblum** [comment] 2022-10-23 09:23
These seem like they may be relevant. Has nothing been done about this issue since 2018?
https://github.com/rust-lang/rust-bindgen/issues/1266
https://github.com/rust-lang/rust-bindgen/issues/1524

**Comment by pvdrz** [comment] 2022-10-24 15:07
I believe that this might still be a upstream issue, see [this](https://github.com/rust-lang/rust-bindgen/issues/1524#issuecomment-466182579) comment. I'll check if this is still the case or not.

**Comment by pvdrz** [comment] 2023-01-10 21:08
I'm closing this as it is a duplicate of https://github.com/rust-lang/rust-bindgen/issues/1266

PD: There has not been any movement from the LLVM side either https://bugs.llvm.org/show_bug.cgi?id=36576

**Closed by pvdrz** 2023-01-10 21:08 UTC
