### ISSUE TITLE
Escape `[` and `]` characters when it's not a link

### ISSUE THREAD

**Issue by inflation** [rust-lang/rust-bindgen#1965] opened 2021-01-08 00:56 UTC
### Input C/C++ Header

```C++
/** The tone mapping will leave unchanged (linear mapping) any pixels whose
 * brightness is strictly below this. The interpretation depends on
 * relative_to_max_display. If true, this is a ratio [0, 1] of the maximum
 * display brightness [nits], otherwise an absolute brightness [nits].
 */
```

### Bindgen Invocation

```Rust
bindgen::Builder::default()
    .header("input.h")
    .generate()
    .unwrap()
```

### Actual Results

```bash
     |
1706 | /     #[doc = " The tone mapping will leave unchanged (linear mapping) any pixels whose"]
1707 | |     #[doc = " brightness is strictly below this. The interpretation depends on"]
1708 | |     #[doc = " relative_to_max_display. If true, this is a ratio [0, 1] of the maximum"]
1709 | |     #[doc = " display brightness [nits], otherwise an absolute brightness [nits]."]
     | |___________________________________________________________________________________^
     |
     = note: `#[warn(broken_intra_doc_links)]` on by default
     = note: the link appears in this line:

             display brightness [nits], otherwise an absolute brightness [nits].
                                 ^^^^
     = note: no item named `nits` in scope
     = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

```

### Expected Results

No warnings.

Maybe this is super low priority, feel free to close it. 😃

**Comment by pvdrz** [comment] 2022-09-09 16:19
This is a duplicate of https://github.com/rust-lang/rust-bindgen/issues/1955

**Closed by pvdrz** 2022-09-09 16:19 UTC
